# Generated by Django 2.1.5 on 2019-05-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_contact_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
